### ISSUE TITLE
Forge 1.20.1

### ISSUE THREAD

**Issue by GRYFFlN** [TechTastic/TIS-VS#1]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

It seems he considers it an error in mod.toml.

apparently it should be like this:
> modLoader="javafml"  # Certifique-se de que o modLoader é o correto.
> loaderVersion="[1.20,)"  # Indica a versão mínima do loader suportada. Aqui, para Minecraft 1.20+.
> [[mods]]
> modId="seu_mod_id"  # Identificador único do seu mod.
> version="${file.jarVersion}"  # Pode ser substituído por uma string fixa, ex.: "1.0.0".
> displayName="Nome do Mod"  # Nome do seu mod.
> description="Descrição do seu mod."  # Descrição que será exibida no menu Mods.
> 
> [[dependencies.seu_mod_id]]
> modId="forge"  # Dependência do Forge.
> mandatory=true  # Esta dependência é obrigatória.
> versionRange="[47.3.1,)"  # Mínimo Forge 47.3.1. Corrija aqui o formato se necessário.
> ordering="NONE"
> side="BOTH"  # Ou CLIENT/SERVER dependendo de onde deve rodar.
> 
> [[dependencies.seu_mod_id]]
> modId="algum_outro_mod"  # Caso o mod dependa de outro.
> mandatory=false  # Dependência opcional.
> versionRange="[1.0,2.0)"  # Versões aceitas entre 1.0 e abaixo de 2.0.
> ordering="NONE"
> side="BOTH"

however, there is a part (advanced tis) that is like this:

> versionRange="[,)"

when it should be like this;

> versionRange="[1.0,)"

### Issue reproduction

adding the tis vs again

### Logs

`[19:59:25] [main/INFO]: ModLauncher running: args [--username, G_R_I_F_I_N, --version, forge-47.3.0, --gameDir, C:\Users\grifo\curseforge\minecraft\Instances\test_ _, --assetsDir, C:\Users\grifo\curseforge\minecraft\Install\assets, --assetIndex, 5, --uuid, cabedb0c5b19406baf6527c82cc4dc59, --accessToken, ????????, --clientId, ZmM2ODc3OWItMDQ5Ny00YTBkLWI5ZmMtODU3ZmI0YWEwNjg2, --xuid, 2535424798820619, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\grifo\curseforge\minecraft\Install\quickPlay\java\1731365962014.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[19:59:25] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[19:59:25] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[19:59:25] [main/INFO]: Trying GL version 4.6
[19:59:26] [main/INFO]: Requested GL version 4.6 got version 4.6
[19:59:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/grifo/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[19:59:26] [pool-2-thread-1/INFO]: GL info: AMD Radeon(TM) Graphics GL version 4.6.0 Core Profile Context 24.10.1.241007, ATI Technologies Inc.
[19:59:26] [main/FATAL]: Failed to parse version spec [,)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Range cannot have identical boundaries: [,)
	at org.apache.maven.artifact.versioning.VersionRange.parseRestriction(VersionRange.java:217) ~[maven-artifact-3.8.5.jar:3.8.5]
	at org.apache.maven.artifact.versioning.VersionRange.createFromVersionSpec(VersionRange.java:146) ~[maven-artifact-3.8.5.jar:3.8.5]
	at net.minecraftforge.forgespi.language.MavenVersionAdapter.createFromVersionSpec(MavenVersionAdapter.java:33) ~[forgespi-7.0.1.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.<init>(ModInfo.java:218) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$7(ModInfo.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:100) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:85) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:86) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[fmlloader-1.20.1-47.3.0.jar:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.20.1-47.3.0.jar:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
`

**Comment by GRYFFlN** [comment]
also.. can you send me the discord link (a valid one)

**Comment by Zundaseki** [comment]
> also.. can you send me the discord link (a valid one)

most certainly would like it too!

**Comment by 74HC14** [comment]
Can confirm, changing that text file in the .jar file prevents the crash on startup. The mod content loads after making this change.

**Comment by TechTastic** [comment]
Should be fixed in latest Release
